services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    networks:
      - gamific

  keycloak:
    command: start-dev --features=preview
    image: quay.io/phasetwo/phasetwo-keycloak:24.0
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - 8080:8080
    networks:
      - gamific

  gamific:
    depends_on:
      - db
    container_name: gamific
    build:
      context: ./gamific
      dockerfile: dev.Dockerfile

    environment:
      DEPLOY_ENV: dev

    volumes:
      - ./gamific/src:/app/src
      - ./gamific/public:/app/public
    restart: always
    ports:
      - 3000:3000
    networks:
      - gamific

  nginx:
    depends_on:
      - gamific
    image: nginx
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - gamific

networks:
  gamific:
    external: false
