services:
  gamific-db:
    image: postgres
    volumes:
      - gamific_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: gamificdb
      POSTGRES_USER: gamific
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    networks:
      - gamific

  keycloak-db:
    image: postgres
    volumes:
      - keycloak_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloakdb
      POSTGRES_USER: gamific
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    networks:
      - gamific

  keycloak:
    command: start-dev --features=preview
    image: quay.io/phasetwo/phasetwo-keycloak:24.0
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: postgres://keycloak-db
      KC_DB_USERNAME: gamific
      KC_DB_PASSWORD: password
    ports:
      - 8080:8080
    networks:
      - gamific
    restart: always
    depends_on:
      - keycloak-db

  gamific:
    depends_on:
      - gamific-db
    container_name: gamific
    build:
      context: ./gamific
      dockerfile: dev.Dockerfile
    environment:
      DEPLOY_ENV: dev
    volumes:
      - ./gamific/src:/app/src
      - ./gamific/public:/app/public
    restart: always
    ports:
      - 3000:3000
    networks:
      - gamific

  nginx:
    depends_on:
      - gamific
    image: nginx
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - gamific

networks:
  gamific:
    external: false

volumes:
  gamific_data:
    driver: local
  keycloak_data:
    driver: local